### ISSUE TITLE
Welcome Jordan

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/Mofo-Design-Handbook#16]
@lovegushwa - Welcome to the team. Reply here with questions or to try things out. I bet @vazquez has some tips for using github issues that he could add here.

**Comment by xmatthewx** [comment]
You can edit this comment with the pencil in the top right to see the `markdown` that made it. :boom: 

 - lists! 
  - sub lists
 - w00t

Here's a link to the [draft process chapter](https://github.com/xmatthewx/Mofo-Design-Handbook/tree/master/Process)

You can link to a different issue with just hashtag + issue number. Ex: #16 

You can link to a specific comment. Click the time in the comment  comment header. Copy the URL. Github will shorten it to make it prettier. For example: https://github.com/mozilla/webmaker-app/issues/1515#issuecomment-98222810

**Comment by cassiemc** [comment]
Closing this since @lovegushwa is rockin' github now.
