### ISSUE TITLE
'First time use' at Whistler

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/Mofo-Design-Handbook#17]
@secretrobotron suggested that FTU for Webmaker would be a great topic to tackle at Whistler. I agree and think we designers could look at this across MoFo products. 

FTU would be fun to think while we're together. It's useful and good to coordinate org-wide. Can we add this to the plan for Wednesday Cassie?

Related - during the science fair, we should watch for FTU pain and opportunities. This event happens before we meet, so let’s try and arrive with this stuff in mind. 

cc: @LauraReynal @lovegushwa @cassiemc @flukeout @vazquez

**Comment by xmatthewx** [comment]
cc @sabrinang woops

**Comment by cassiemc** [comment]
We didn't get to this and I'm assuming it's filed elsewhere in the webmaker plan, so closing. cc @xmatthewx
