### ISSUE TITLE
Discuss design team here

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/Mofo-Design-Handbook#18]
Let's use this repo (or create a new one) to discuss design team topics. Even suggested articles could be posted here, labelled and make a nice archive. 

**What do you think?** R?

Related: Let's try to include @LauraReynal as often as possible. I'm going to try and tighten the loop between design, tests, and research in Q3 and Q4. 

cc @cassiemc @lovegushwa @flukeout @vazquez @sabrinang

**Comment by cassiemc** [comment]
Wfm. Open FTW!
